{
 "title": "Mixins Druid",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(druid_emitted_metrics, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(druid_emitted_metrics, instance)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(druid_emitted_metrics, host)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(druid_emitted_metrics, service)"
    }
   },
   {
    "name": "druiddatasource",
    "query": {
     "query": "label_values(druid_datasource, datasource)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "druid_health_status{job =~ \"${job}\"}"
    }
   ]
  },
  {
   "title": "Datasources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(druid_datasource{job =~ \"$job\"})"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SUM(druid_segment_count{job =~ \"$job\",datasource_name =~ \"$druiddatasource\"})"
    }
   ]
  },
  {
   "title": "Segments size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SUM(druid_segment_size{job =~ \"$job\",datasource_name =~ \"$druiddatasource\"})/(1048576)"
    }
   ]
  },
  {
   "title": "Average segment size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SUM(druid_segment_size{job =~ \"$job\",datasource_name =~ \"$druiddatasource\"})/((1048576)*SUM(druid_segment_count{job =~ \"$job\",datasource_name =~ \"$druiddatasource\"}))"
    }
   ]
  },
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Running tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"RUNNING\", datasource=~\"$druiddatasource\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Completed tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status!=\"RUNNING\", datasource=~\"$druiddatasource\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Succeeded tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"SUCCESS\", datasource=~\"$druiddatasource\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Task's success ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"SUCCESS\", job=~\"$job\", datasource=~\"$druiddatasource\"}) / count(druid_tasks_duration{task_status!=\"RUNNING\", job=~\"$job\", datasource=~\"$druiddatasource\"}) * 100",
     "legendFormat": "Tasks success ratio"
    }
   ]
  },
  {
   "title": "Failed tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"FAILED\", datasource=~\"$druiddatasource\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of supervisors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(druid_supervisors{job =~ \"$job\",supervisor_name =~ \"$druiddatasource\"})"
    }
   ]
  },
  {
   "title": "Number of supervisors per state",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (state) (druid_supervisors{job =~ \"$job\", supervisor_name =~ \"$druiddatasource\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Processed events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(druid_emitted_metrics{metric_name=\"ingest-events-processed\", job=~\"$job\", datasource=~\"$druiddatasource\", host=~\"$host\"}[$__range])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Persisted events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(druid_emitted_metrics{metric_name=\"ingest-persists-count\", job=~\"$job\", datasource=~\"$druiddatasource\", host=~\"$host\"}[$__range])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Rejected events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(druid_emitted_metrics{metric_name=\"ingest-events-thrownAway\", job=~\"$job\", datasource=~\"$druiddatasource\", host=~\"$host\"}[$__range])) by (host)",
     "legendFormat": "ThrownAway {{host}}"
    },
    {
     "expr": "sum(increase(druid_emitted_metrics{metric_name=\"ingest-events-unparseable\", job=~\"$job\", datasource=~\"$druiddatasource\", host=~\"$host\"}[$__range])) by (host)",
     "legendFormat": "Unparseable {{host}}"
    },
    {
     "expr": "sum(increase(druid_emitted_metrics{metric_name=\"ingest-events-duplicate\", job=~\"$job\", datasource=~\"$druiddatasource\", host=~\"$host\"}[$__range])) by (host)",
     "legendFormat": "Duplicated {{host}}"
    }
   ]
  },
  {
   "title": "Kafka Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(druid_emitted_metrics{metric_name=\"ingest-kafka-lag\", job=~\"$job\", datasource=~\"$druiddatasource\"}[$__range])) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(druid_emitted_metrics{metric_name=\"jvm-mem-used\", job=~\"$job\"}[$__range])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(druid_emitted_metrics{metric_name=\"jvm-pool-used\",job=~\"$job\"}[$__range])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}